//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quanlythuvien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocGia
    {
        public string MaDocGia { get; set; }
        public string TenDocGia { get; set; }
        public string MaSo { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public Nullable<int> Khoa { get; set; }
        public string SDT { get; set; }
        public string GioiTinh { get; set; }
    }
}
