//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quanlythuvien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MuonSach
    {
        public string MaPhieu { get; set; }
        public string MaDocGia { get; set; }
        public Nullable<System.DateTime> NgayMuon { get; set; }
        public Nullable<System.DateTime> NgayHenTra { get; set; }
        public Nullable<System.DateTime> NgayLapPhieu { get; set; }
        public string MaNV { get; set; }
        public string MaSach { get; set; }
    }
}
