//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quanlythuvien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sach
    {
        public string MaSach { get; set; }
        public string TenSach { get; set; }
        public Nullable<int> Id_TL { get; set; }
        public string TacGia { get; set; }
        public string NhaXB { get; set; }
        public Nullable<int> TinhTrang { get; set; }
    }
}
